name: Linux Transformers Test

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/scripts/spec.py'
      - '.github/workflows/_linux_transformers.yml'
  workflow_dispatch:
    inputs:
      pytorch:
        required: false
        type: string
        default: 'nightly'
        description: Pytorch branch/commit
      python:
        required: false
        type: string
        default: '3.10'
        description: Python version
      runner:
        required: true
        type: string
        default: 'linux.idc.xpu'
        description: Runner label
      driver:
        required: false
        type: string
        default: 'lts'
        description: Driver lts/rolling
      nightly_whl:
        required: false
        type: string
        default: ''
        description: Pytorch nightly wheel version
      transformers:
        required: false
        type: string
        default: 'v4.47.0'
        description: Transformers version

permissions: read-all

jobs:
  Torch-XPU-Transformers-Tests:
    runs-on: ${{ inputs.runner != '' && inputs.runner || 'ubuntu-24.04' }}
    env:
      NEOReadDebugKeys: ${{ inputs.driver == 'rolling' && '1' || '0' }}
      DisableScratchPages: ${{ inputs.driver == 'rolling' && '1' || '0' }}
      python: ${{ inputs.python != '' && inputs.python || '3.10' }}
      pytorch: ${{ inputs.pytorch != '' && inputs.pytorch || 'nightly' }}
      transformers: ${{ inputs.transformers != '' && inputs.transformers || 'v4.47.0' }}
      TRANSFORMERS_TEST_DEVICE_SPEC: 'spec.py'
    steps:
      - name: Checkout torch-xpu-ops
        uses: actions/checkout@v4
        with:
          path: torch-xpu-ops
      - name: Checkout Transformers
        uses: actions/checkout@v4
        with:
          repository: huggingface/transformers
          ref: ${{ env.transformers }}
          path: transformers
      - name: Prepare Conda ENV
        run: |
          which conda && conda clean -ay
          conda remove --all -y -n huggingface_transformers_test || rm -rf $(dirname ${CONDA_EXE})/../envs/huggingface_transformers_test
          conda create -y -n huggingface_transformers_test python=${{ env.python }}
          source $CONDA/bin/activate huggingface_transformers_test
      - name: Sanity check Conda environment
        run: |
          test "$CONDA_DEFAULT_ENV" = huggingface_transformers_test
